color: green
fieldLayouts:
  68e690a6-82bc-4a9f-8a1d-bd86c282d90a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bf3de89f-657a-43ea-bb2d-16df289e31f2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e382f540-6622-4500-804d-034bf966905c # SectionTitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54b50d08-2b2f-47c0-86ea-1674948017a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 485aa77d-cdbd-41f9-b327-610c6c182c10 # Section Bodytext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9eb0d012-c0df-4379-8004-3f3ecce79a4e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b8d5053-b878-4432-8068-0265cc4a31c2 # Form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa18d939-9d20-48e7-8a1f-4441275ff268
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e8f0e4cc-cd4d-4e03-89d6-8f139a9a28bc
        userCondition: null
handle: formBlock
hasTitleField: true
icon: input-text
name: 'Form Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
