color: pink
fieldLayouts:
  1e9e1028-a121-480d-b35a-19cc1927da9a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 279d6604-94a4-4f9a-b1fc-bbaa7b0a2758
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e382f540-6622-4500-804d-034bf966905c # SectionTitle
            handle: brandTitle
            includeInCards: false
            instructions: 'Add the brand name title here'
            label: 'Brand Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a5a96b8-d030-4231-8375-3e84789466de
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85dfc3a4-6078-4b40-8343-342993c4bb48 # Address line
            handle: productsLink
            includeInCards: false
            instructions: 'Link to products'
            label: 'Products Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1dfa55f-8217-4405-a241-0e989ae99dfe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85dfc3a4-6078-4b40-8343-342993c4bb48 # Address line
            handle: contactLink
            includeInCards: false
            instructions: 'Add the contact Link'
            label: 'Contact Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3195872-4f42-4e13-bf7e-d3be5406d3a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 85dfc3a4-6078-4b40-8343-342993c4bb48 # Address line
            handle: cartLink
            includeInCards: false
            instructions: 'Add the Cart link title'
            label: 'Cart Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1dedea0d-673a-4458-97e0-21df986a74d7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ecf08738-def7-40fb-92d9-f458d6926431 # Login Button
            handle: loginButton
            includeInCards: false
            instructions: 'Add login button text'
            label: LoginButton
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b4ee2b9-2f58-4d7a-9983-5881d1406942
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ae67048d-23f6-4ea9-9fdc-b599d8dce708
        userCondition: null
handle: navbarContent
hasTitleField: true
icon: arrow-up
name: 'Navbar Content'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
