color: violet
fieldLayouts:
  28fd6328-b1a7-484b-867b-c7c17fe9c3a3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ea402507-2cd4-46a9-a36b-b13dbbbff204
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 98c3dc06-93d3-4762-a012-2f5e3e528199 # Price
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 836dfed1-d421-427e-b598-cd67abb7e642
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae793556-b602-4d72-89b3-113498ec50ee # Product Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef190e0d-a134-418e-9999-9d9ee74daf32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c9b1183-2e60-43fd-944e-8169ff86fa56 # productbutton
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13e413ba-f3d6-4c38-9a2e-ffcc4195debf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 291a5e20-cc3e-4d3b-9ea6-acfd998fb2ae # Product Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2acee50b-1cde-4d9a-a18a-ca37d2b8f157
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 06d32b3a-f5d6-4def-8c52-7cc3811619ec
        userCondition: null
handle: productCard
hasTitleField: true
icon: diamond
name: 'Product Card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
