color: green
fieldLayouts:
  8fc3cedc-e142-4ad8-9cd4-19f8cbfe5fce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a7686840-0943-4a1f-91e6-28b59b650009
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1c126ecf-61ff-426f-a3cf-32d1da623158 # Products Field
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8509038-2fdc-40dd-b41c-6141dfe4cae8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68d8247f-cb74-45e8-b549-86242b6aac3b
        userCondition: null
handle: productsBlock
hasTitleField: true
icon: album
name: 'Products Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
