color: orange
fieldLayouts:
  50b480e6-4f5a-49d8-af9a-542804d4fa4d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 999210f7-f087-44b7-a9ee-56ae02808784
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 548730d6-8c6c-48bf-8ead-2ea64fb63952 # Description Large
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d27701b-8923-45df-ad70-9d483e737d6a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 98c3dc06-93d3-4762-a012-2f5e3e528199 # Price
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa53710f-58d6-4172-a61d-736fe14b0b8e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 291a5e20-cc3e-4d3b-9ea6-acfd998fb2ae # Product Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f96abea9-20b1-47fe-97b7-1d0c1c5deae3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae793556-b602-4d72-89b3-113498ec50ee # Product Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b926feee-ba62-4b0a-8b61-dc94ae1efe6a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b186655c-2d7c-4ee5-adbf-e987913ef15f # Product Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad3cbc01-9c4e-49c5-804b-535577498400
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae6b26e1-b817-41a9-89ca-0de5e4d3cc5b # Product Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bb496c8-bdd0-4c15-8208-12163ef910dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9dbbf173-7317-4124-a03d-dabbe8564bfb # Product Rating
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebf20a62-5898-48bb-8645-121c58205909
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c9b1183-2e60-43fd-944e-8169ff86fa56 # Productcard - Button Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64a40f43-1765-4072-9211-86ebdfa023a6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c9bc4e7-c0d6-4732-9bc8-851fbc9151fd
        userCondition: null
handle: productEntry
hasTitleField: true
icon: amp-guitar
name: 'Product Entry'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
