color: blue
fieldLayouts:
  6e5640ce-c288-4096-a747-83c53221f0bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 26b632cd-2b79-49b3-8756-cac2dc00d94e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 818b0433-7a51-4cd8-96f4-2022cffcc1f7 # Heading Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee71d78e-23d9-4cc9-a302-fab136b5b77f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a79f21c3-a954-495d-8f94-8b6fc88377b7 # Page Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd45a7a2-d9b1-497d-9f0f-c787399dac4d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 343020c3-c870-47bc-ba0c-057c1a270c49
        userCondition: null
handle: productpageEntry
hasTitleField: true
icon: bag-shopping
name: 'ProductPage Entry'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
