color: green
fieldLayouts:
  304459a4-6711-4ea5-8ed5-b4c0e9d24d3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 312c372d-c8a0-4fbc-8544-5e2bc6d59573
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 38dc8a23-2a19-4a1c-88fb-53a74646a7cc # text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73398c98-d8a3-4782-a522-a6a69539fae8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bfa74cfc-5409-45e2-9828-99f7d84b23ab # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fde72403-c822-46e2-ae20-72b333795cbd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80a44a27-d35a-41a6-8cd4-669d60710925 # Dropdown L/R
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a51e5ae-8e35-467f-96f8-38cab122eb55
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0cdb91d0-d08f-413b-bd69-9157eccb92e9 # Toggle Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e01af891-47aa-43bd-a8ea-e86033125e9e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 328fb5dd-95b2-4583-99aa-901dc975b003
        userCondition: null
handle: textImageBlock
hasTitleField: true
icon: image-polaroid
name: 'Text + Image Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
