color: green
fieldLayouts:
  b828721e-93ec-4118-9dd0-f5981b5da832:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 11903379-fe4e-4d4f-a363-f745fc5ac1af
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 859491cf-e25a-4377-b2d0-a631dc258b03
        userCondition: null
handle: text
hasTitleField: true
icon: text
name: Text
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
