defaultPlacement: end
fieldLayouts:
  0fc35be4-8b7b-4098-be63-10565e298ebb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: a6a92fa4-9c0d-484e-915d-0518b16e5e1c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4118e006-4631-4053-881a-624061e01e19
        userCondition: null
handle: productCategories
name: 'Product Categories'
siteSettings:
  2b1f5981-d58e-4a2f-8225-ee102113ad97: # Auro Craft - Nederlands
    hasUrls: true
    template: products/_category.twig
    uriFormat: 'products/categories/{slug}'
  c8882d7d-4c84-40d3-a270-4653a2dfec91: # auro-craft
    hasUrls: true
    template: products/_category.twig
    uriFormat: 'products/categories/{slug}'
structure:
  maxLevels: 1
  uid: f1254012-2171-4508-b4b3-ed8766b74fa8
