altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  0aebf13c-de02-48a0-a08f-3a7c79ac3e46:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 79610dc5-441f-49cd-8ea9-6857895c4699
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c960fce8-ec4b-4ea8-b20f-b50c83e8a30b
        userCondition: null
fs: images
handle: images
name: images
sortOrder: 7
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
