columnSuffix: null
handle: headingSubtitle
instructions: 'Add a subtitle for the page'
name: 'Page Subtitle'
searchable: true
settings:
  byteLimit: null
  charLimit: 64
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
