columnSuffix: null
handle: headingTitle
instructions: 'Add the page heading title here.'
name: 'Heading Title'
searchable: true
settings:
  byteLimit: null
  charLimit: 180
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Page heading placeholder.'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
