columnSuffix: null
handle: productButtonText
instructions: 'add product button text'
name: 'Productcard - Button Text'
searchable: false
settings:
  byteLimit: null
  charLimit: 48
  code: false
  initialRows: 4
  multiline: false
  placeholder: Details
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
