columnSuffix: null
handle: productRating
instructions: 'Add the star rating of the product here (range 1 - 5)'
name: 'Product Rating'
searchable: false
settings:
  decimals: 0
  defaultValue: 5
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
