columnSuffix: null
handle: sectiontitle
instructions: 'Add a title for the transition section'
name: SectionTitle
searchable: true
settings:
  byteLimit: null
  charLimit: 64
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Placeholder Section Title'
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
