columnSuffix: null
handle: stock
instructions: 'Add the amount of stock available for the product.'
name: Stock
searchable: false
settings:
  decimals: 0
  defaultValue: 5
  max: 120
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
