columnSuffix: null
handle: text
instructions: 'Add some body text for your page'
name: text
searchable: false
settings:
  byteLimit: null
  charLimit: 900
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
