fieldLayouts:
  07ec9f52-5639-4db1-9114-bddb265129f8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 49fade99-c7c8-477b-a9d3-881c8d99d1b0 # Social Link
            handle: instagram
            includeInCards: false
            instructions: 'Add instagram link'
            label: Instagram
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5ac05f5-888a-4968-b20c-2b77d3623076
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 49fade99-c7c8-477b-a9d3-881c8d99d1b0 # Social Link
            handle: snapchat
            includeInCards: false
            instructions: 'Add link for Snapchat'
            label: Snapchat
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ee095dd-51f5-4db7-8576-7f8dd615f1d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 49fade99-c7c8-477b-a9d3-881c8d99d1b0 # Social Link
            handle: facebook
            includeInCards: false
            instructions: 'Add facebook link'
            label: Facebook
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ed58cc5-ce19-41c0-8849-6434de918419
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 49fade99-c7c8-477b-a9d3-881c8d99d1b0 # Social Link
            handle: youtube
            includeInCards: false
            instructions: 'Add a youtube link'
            label: Youtube
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25d7566f-5327-4858-b7fe-b7229bf5aee7
            userCondition: null
            warning: null
            width: 100
        name: 'Social Links'
        uid: 4bceb868-c464-4f5d-884b-9bc723c81a43
        userCondition: null
handle: socialLinks
name: 'Social Links'
sortOrder: 2
