defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2b50aeaf-630e-40de-9f85-5722be92682b # Product Card
handle: productsTest
maxAuthors: 1
name: 'Products Test'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c8882d7d-4c84-40d3-a270-4653a2dfec91: # auro-craft
    enabledByDefault: true
    hasUrls: true
    template: _products/_product.twig
    uriFormat: 'products-test/{slug}'
type: channel
